version: "3"
services:

    api:
        build: .
        depends_on:
            - db
            - test-db
        ports: 
            - 8000:8000
        env_file:
            - ./.env
        volumes:
            - ./:/usr/src/app:ro
        command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    
    db:
        image: postgres:14
        environment:
            - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
            - POSTGRES_DB=${DATABASE_NAME}

        volumes:
            - db_data:/var/lib/postgresql/data

    test-db:
        image: postgres:14
        environment:
            - POSTGRES_PASSWORD=${TEST_DATABASE_PASSWORD}
            - POSTGRES_DB=${TEST_DATABASE_NAME}

        volumes:
            - test_db_data:/var/lib/postgresql/data

volumes:
    db_data:
    test_db_data: