version: "3"
services:
    
    # API container
    api:
        build: .
        # start up the DB first
        depends_on:
            - db
        ports: 
            - 8000:8000
        env_file:
            - ./.env
        volumes:
            - ./:/usr/src/app:ro
        command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    
    # DB container
    db:
        image: postgres
        environment:
            - POSTGRES_PASSWORD=password123
            - POSTGRES_DB=bugtracker-db

        # Postgres data will be stored here
        volumes:
            - db_data:/var/lib/postgresql/data

volumes:
    db_data: