version: "3"
services:
    
    # API container
    api:
        image: yuio3owl/bugtracker:latest

        # start up the DB first
        depends_on:
            - db
        ports: 
            - 80:8000
        environment:
            - DATABASE_HOSTNAME=${DATABASE_HOSTNAME}
            - DATABASE_PORT=${DATABASE_PORT}
            - DATABASE_PASSWORD=${DATABASE_PASSWORD}
            - DATABASE_NAME=${DATABASE_NAME}
            - DATABASE_USERNAME=${DATABASE_USERNAME}
            - SECRET_KEY=${SECRET_KEY}
            - ALGORITHM=${ALGORITHM}
            - ACCESS_TOKEN_EXPIRE_MINUTES=${ACCESS_TOKEN_EXPIRE_MINUTES}
    
    # DB container
    db:
        image: postgres
        environment:
            - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
            - POSTGRES_DB=${DATABASE_NAME}

        # Postgres data will be stored here
        volumes:
            - db_data:/var/lib/postgresql/data

volumes:
    db_data: